name: VTalk AOT build(generated native code)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  raspbarry-pi-build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Gluon's GraalVM
        uses: gluonhq/setup-graalvm@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install libraries
        run: |
          sudo apt-get update
          sudo apt install libasound2-dev libavcodec-dev libavformat-dev libavutil-dev libgl-dev libgtk-3-dev libpango1.0-dev libxtst-dev
          sudo apt install g++-aarch64-linux-gnu
      - name: Make staging directory
        run: mkdir staging

      - name: Gluon Build
        run: mvn -Ppi gluonfx:build gluonfx:package

      - name: Copy native image to staging
        run: cp -r target/gluonfx/aarch64-linux/VTalk* staging

      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: VTalk-Raspberry-Pi
          path: staging
          retention-days: 1